server:
  port: 8000

test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  #  uri: http://${test.hostport}
  uri: lb://httpbin

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:

      routes:
        - id: user
          uri: lb://user-server:9000
          order: 9000
          predicates:
            - Path=/users/all
        - id: calories
          uri: lb://calories-server:9200
          order: 9200
          predicates:
            - Path=/calories/all
        - id: steps
          uri: lb://steps-server:9100
          order: 9100
          predicates:
            - Path=/steps/all
        - id: auth
          uri: lb://auth-server:8004
          order: 8004
          predicates:
            - Path=/auth/hello

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG



#management.endpoints.web.exposure.include: '*'
