server:
  port: 8000

test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  #  uri: http://${test.hostport}
  uri: lb://httpbin

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:

      routes:
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/users/**
        - id: calories
          uri: lb://calories-server
          predicates:
            - Path=/calories/**
        - id: steps-server
          uri: lb://steps-server
          predicates:
            - Path=/steps/**
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG



#management.endpoints.web.exposure.include: '*'
